### ISSUE TITLE
db create have some error

### ISSUE THREAD

**Issue by lvkasi** [mallowlabs/redmine-oauth-plugin#1]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
Migrating clipboard_image_paste (Clipboard image paste)...
Migrating csv_import_issues (csv_import_issues)...
Migrating csv_import_users (redmine_csv_import_users)...
Migrating redmine_code_review (Redmine Code Review plugin)...
Migrating redmine_lightbox2 (Redmine Lightbox 2)...
Migrating redmine_oauth_provider (Redmine Oauth Provider plugin)...
== 1 CreateOauthTables: migrating =============================================
-- create_table(:client_applications)
   -> 0.0031s
-- add_index(:client_applications, :key, {:unique=>true})
   -> 0.0073s
-- create_table(:oauth_tokens)
   -> 0.0017s
-- add_index(:oauth_tokens, :token, {:unique=>true})
   -> 0.0073s
-- create_table(:oauth_nonces)
   -> 0.0014s
-- add_index(:oauth_nonces, [:nonce, :timestamp], :unique)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `assert_valid_keys' for :unique:Symbol/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:875:in `add_index_options'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:526:in `add_index'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:417:in `method_missing'
/data/redmine/plugins/redmine_oauth_provider/db/migrate/001_create_oauth_tables.rb:37:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:569:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/data/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/redmine/lib/redmine/plugin.rb:459:in `each'
/data/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `assert_valid_keys' for :unique:Symbol
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:875:in `add_index_options'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:526:in `add_index'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:417:in `method_missing'
/data/redmine/plugins/redmine_oauth_provider/db/migrate/001_create_oauth_tables.rb:37:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:569:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/data/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/redmine/lib/redmine/plugin.rb:459:in `each'
/data/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by suer** [comment]
It is a error to migrate DB of redmine_oauth_provider.
 I fixed this issue at HEAD of [suer/redmine_oauth_provider](https://github.com/suer/redmine_oauth_provider).
Please check HEAD of redmine_oauth_provider and try again.
