### ISSUE TITLE
help：how can i get Redmine OAuth Plugin of jenkins? 

### ISSUE THREAD

**Issue by lvkasi** [mallowlabs/redmine-oauth-plugin#2]
~~~
Second, you need to configure your Jenkins.

Open Jenkins Configure System page.
Check Enable security.
Select Redmine OAuth Plugin in Security Realm.
Input your Redmine Url to Redmine Url.
Input your Consumer Key to Client ID.
Input your Consumer Secret to Client Secret.
Click Save button.
~~~

in this step,how can i get **Redmine OAuth Plugin** of **jenkins**? thanks.

**Comment by mallowlabs** [comment]
Redmine OAuth Plugin is not hosted on Jenkins Update Center.
You need to build plugin from source or download built plugin ( https://jitpack.io/com/github/mallowlabs/redmine-oauth-plugin/330130879f/redmine-oauth-plugin-330130879f.hpi )

After getting .hpi file, you need to upload .hpi file to your Jenkins plugin page.

**Comment by lvkasi** [comment]
So this is ah，thanks
